package presentacio;

import domini.Clases.ExprBooleana;
import domini.exceptions.ExprMalFormadaException;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Aquesta vista s'encarrega de fer creacio d'expressions booleanes
 */

public class vistaAltaExpressio extends JFrame {
    /**
     * Boto per finalitzar proces de creacio d'expressio booleana i crear la expressio booleana
     */
    private JButton bAlta;

    /**
     * Boto per tornar al gestor de expressions booleanes
     */
    private JButton bSortir;
    /**
     * Titol de la vista
     */
    private JLabel titolVista;

    /**
     * El panell que conte tots components de finestra
     */
    private JPanel lamina;
    /**
     * Area de text per introduir una expressio
     */
    private JTextArea expressio;

    public vistaAltaExpressio() {
        setContentPane(lamina);
        setVisible(true);
        setBounds(500, 300, 500, 300);

        bAlta.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean exit = true;


                try {
                    if (!expressio.getText().isEmpty()) {
                        CtrlPresentacio.altaExpressioBooleana(expressio.getText());
                    } else {
                        new Missatge("L'expressio no pot ser buida");
                        exit = false;
                    }
                } catch (ExprMalFormadaException ex) {
                    exit = false;
                    new Missatge(ex.getMessage());
                }


                if (exit) {
                    new Missatge("L'expressio s'ha creat correctament");
                }
                expressio.setText("Introdueix expressio");
            }
        });

        bSortir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaGestorExpr();
                setVisible(false);
                dispose();
            }
        });

        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        lamina = new JPanel();
        lamina.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        lamina.add(panel1, BorderLayout.SOUTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.NORTH);
        bAlta = new JButton();
        bAlta.setText("Alta");
        panel2.add(bAlta);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel3, BorderLayout.SOUTH);
        bSortir = new JButton();
        bSortir.setText("Sortir");
        panel3.add(bSortir);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        lamina.add(panel4, BorderLayout.NORTH);
        titolVista = new JLabel();
        titolVista.setText("Alta expressio booleana");
        panel4.add(titolVista, BorderLayout.SOUTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        lamina.add(scrollPane1, BorderLayout.CENTER);
        expressio = new JTextArea();
        expressio.setLineWrap(true);
        expressio.setText("Introdueix expressio");
        scrollPane1.setViewportView(expressio);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return lamina;
    }

}
