package presentacio;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 * Aquesta vista s'encarrega de mostrar totes funcionalitats que es poden fer amb consultes i
 * permet anar a la vista que pot realitzar aquestes funcionalitats amb botons
 * @author Zheshuo Lin
 */
public class vistaGestorConsulta extends JFrame {

    /**
     * El panell que conte tots components de finestra
     */
    private JPanel lamina;
    /**
     * Títol de la finestra
     */
    private JLabel titolVista;
    /**
     * boto per tancar la finestra i tornar al menu principal
     */
    private JButton bSortir;
    /**
     * Boto per anar a la finestra per ordenar consulta
     */
    private JButton bOrdenar;
    /**
     * Boto per anar a la finestra per operar consulta
     */
    private JButton bOperar;
    /**
     * boto per anar a la finestra de realitzar nova consulta
     */
    private JButton bNovaConsulta;

    public vistaGestorConsulta() {
        setBounds(500, 300, 500, 300);
        setResizable(true);
        setTitle("Gestor De Consulta");
        setContentPane(lamina);

        bSortir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.iniPresentacio();
                setVisible(false);
                dispose();

            }
        });

        bNovaConsulta.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaNovaConsulta();
                setVisible(false);
                dispose();
            }
        });

        bOperar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaOperarConsulta();
                setVisible(false);
                dispose();
            }
        });

        bOrdenar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaOrdenarConsulta();
                setVisible(false);
                dispose();
            }
        });


        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        lamina = new JPanel();
        lamina.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        lamina.add(panel1, BorderLayout.SOUTH);
        bSortir = new JButton();
        bSortir.setText("sortir");
        panel1.add(bSortir);
        titolVista = new JLabel();
        titolVista.setText("Gestor de consultes");
        lamina.add(titolVista, BorderLayout.NORTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        lamina.add(panel2, BorderLayout.CENTER);
        bNovaConsulta = new JButton();
        bNovaConsulta.setText("Nova consulta");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(bNovaConsulta, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer1, gbc);
        bOrdenar = new JButton();
        bOrdenar.setText("Ordenar consulta");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(bOrdenar, gbc);
        bOperar = new JButton();
        bOperar.setText("Operar consulta");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(bOperar, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return lamina;
    }

}
