package presentacio;

import domini.Clases.ExprBooleana;

import javax.swing.*;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Map;

/**
 * Aquesta vista s'encarrega de modificar una expressio booleana
 */

public class vistaModificarExpr extends JFrame {
    /**
     * El panell que conte tots components de finestra
     */
    private JPanel lamina;
    /**
     * Boto per iniciar proces de modificar la expressio
     */
    private JButton bModificar;

    /**
     * Boto per tornar al gestor de expressions
     */
    private JButton bSortir;
    /**
     * Titol de la vista
     */
    private JLabel titolVista;
    /**
     * Area per seleccionar expressions
     */
    private JList expressions;
    /**
     * Titol de l'area de text per introduir identificador
     */
    private JLabel lIdentificador;
    /**
     * Area de text per introduir identificador
     */
    private JTextArea identificador;
    /**
     * per mostrar a la pantalla les expressions
     */
    private JTextArea infoExpressions;

    /**
     * Vista per fer modificacions
     */
    private JFrame pModificacio = new JFrame();

    public vistaModificarExpr() {
        setTitle("Modificar expressio");
        setContentPane(lamina);
        setBounds(500, 300, 500, 300);
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        bSortir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaGestorExpr();
                setVisible(false);
                dispose();
            }
        });

        Map<Integer, ExprBooleana> exprs = CtrlPresentacio.getExpressions();

        DefaultListModel texprs = new DefaultListModel();

        for (Integer i : exprs.keySet()) {
            String expr = exprs.get(i).getExpresio();
            texprs.addElement(i + ": " + expr);
            infoExpressions.append("Expressio " + i + " " + expr + "\n");
        }
        expressions.setModel(texprs);

        expressions.addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (expressions.getValueIsAdjusting()) {
                    String s = (String) expressions.getSelectedValue();
                    String[] at = s.split(":");
                    identificador.setText(at[0]);
                }
            }
        });

        bModificar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                try {
                    int id = Integer.parseInt(identificador.getText());

                    if (pModificacio.isVisible()) {
                        new Missatge("No pot modificar dues expressions alhora");
                    } else if (exprs.containsKey(id)) {
                        String expressio = exprs.get(id).getExpresio();
                        pModificacio = new vistaModificacioExpr(id, expressio);
                        setVisible(false);
                        dispose();

                    } else {
                        new Missatge("La expressio amb identificador " + identificador.getText() + " no existeix");
                    }
                } catch (NumberFormatException ex) {
                    new Missatge("Identificador ha de ser un nombre");
                }
            }
        });


    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        lamina = new JPanel();
        lamina.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        lamina.add(panel1, BorderLayout.SOUTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel2, BorderLayout.NORTH);
        bModificar = new JButton();
        bModificar.setText("Modificar");
        panel2.add(bModificar);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(panel3, BorderLayout.SOUTH);
        bSortir = new JButton();
        bSortir.setText("Sortir");
        panel3.add(bSortir);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        lamina.add(panel4, BorderLayout.NORTH);
        titolVista = new JLabel();
        titolVista.setText("Modificar expressio booleana");
        panel4.add(titolVista, BorderLayout.NORTH);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        panel4.add(panel5, BorderLayout.SOUTH);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setPreferredSize(new Dimension(256, 64));
        panel5.add(scrollPane1, BorderLayout.CENTER);
        expressions = new JList();
        scrollPane1.setViewportView(expressions);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel4.add(panel6, BorderLayout.CENTER);
        lIdentificador = new JLabel();
        lIdentificador.setText("identificador");
        panel6.add(lIdentificador);
        identificador = new JTextArea();
        identificador.setLineWrap(true);
        identificador.setMinimumSize(new Dimension(100, 15));
        panel6.add(identificador);
        final JScrollPane scrollPane2 = new JScrollPane();
        lamina.add(scrollPane2, BorderLayout.CENTER);
        infoExpressions = new JTextArea();
        infoExpressions.setEditable(false);
        infoExpressions.setLineWrap(true);
        scrollPane2.setViewportView(infoExpressions);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return lamina;
    }

}
