package presentacio;

import javax.swing.*;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;


/**
 * Aquesta vista s’encarrega de mostrar menu principal
 *
 * @author Zheshuo Lin
 */
public class vistaMenuPrincipal extends JFrame {

    /**
     * El panell que conte tots components de finestra
     */
    private JPanel lamina;
    /**
     * Títol de la finestra
     */
    private JLabel titolVista;
    /**
     * Botó per anar a la finestra de gestor de document
     */
    private JButton bDocGestor;
    /**
     * Botó per anar a la finestra de gestor de consulta
     */
    private JButton bConsultaGestor;
    /**
     * Botó per anar a la finestra de gestor de expressio Booleana
     */
    private JButton bExprGestor;

    /**
     * Botó de sortir per a tancar el programa
     */
    private JButton bSortir;
    /**
     * Boto per guardar les dades
     */
    private JButton bGuardar;
    /**
     * Boto per carregar les dades
     */

    private JButton bCarregar;

    public vistaMenuPrincipal() {
        setBounds(500, 300, 500, 300);
        setResizable(true);
        setTitle("File System");
        setContentPane(lamina);


        bExprGestor.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaGestorExpr();
                setVisible(false);
                dispose();
            }
        });
        bDocGestor.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaGestorDocument();
                setVisible(false);
                dispose();
            }
        });

        bConsultaGestor.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaGestorConsulta();
                setVisible(false);
                dispose();
            }
        });
        bSortir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);

            }
        });

        bGuardar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean exit = true;
                try {
                    CtrlPresentacio.guardarConfig();
                } catch (IOException ex) {
                    new Missatge(ex.getMessage());
                    exit = false;
                } catch (ClassNotFoundException ex) {
                    new Missatge(ex.getMessage());
                    exit = false;
                }
                if (exit) {
                    new Missatge("Les dades s'han guardat correctament");
                }
            }
        });

        bCarregar.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean exit = true;
                try {
                    CtrlPresentacio.carregarConfig();
                } catch (IOException ex) {
                    new Missatge(ex.getMessage());
                    exit = false;
                } catch (ClassNotFoundException ex) {
                    new Missatge(ex.getMessage());
                    exit = false;
                }
                if (exit) {
                    new Missatge("Les dades s'han carregat correctament");
                }

            }
        });


        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        lamina = new JPanel();
        lamina.setLayout(new BorderLayout(0, 0));
        titolVista = new JLabel();
        titolVista.setText("File System");
        lamina.add(titolVista, BorderLayout.NORTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        lamina.add(panel1, BorderLayout.SOUTH);
        bSortir = new JButton();
        bSortir.setText("sortir");
        panel1.add(bSortir);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        lamina.add(panel2, BorderLayout.CENTER);
        bDocGestor = new JButton();
        bDocGestor.setText("Gestor De Document");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(bDocGestor, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(spacer1, gbc);
        bExprGestor = new JButton();
        bExprGestor.setText("Gestor De Expressio Booleana");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(bExprGestor, gbc);
        bConsultaGestor = new JButton();
        bConsultaGestor.setText("Gestor De Consulta");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(bConsultaGestor, gbc);
        bGuardar = new JButton();
        bGuardar.setText("Guardar Configuracio");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(bGuardar, gbc);
        bCarregar = new JButton();
        bCarregar.setText("Carregar Configuracio");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel2.add(bCarregar, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return lamina;
    }

}
