package presentacio;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Map;


/**
 * Aquesta vista s'encarrega de crear un nou document
 *
 * @author Zheshuo Lin
 */
public class vistaNouDoc extends JFrame {
    /**
     * El panell que conte tots components de finestra
     */
    private JPanel lamina = new JPanel();
    /**
     * pantalla per introduir contingut de document
     */
    private JFrame pcreacio = new JFrame("pantalla de creacio");

    /**
     * boto per tancar la finestra i tornar a la pantalla anterior
     */
    private JButton bSortir = new JButton("Sortir");
    /**
     * boto per iniciar proces de creacio
     */
    private JButton bCrear = new JButton("Iniciar Creacio");


    /**
     * Area de text per introduir autor
     */
    private JTextArea autor = new JTextArea();
    /**
     * Area de text per introduir titol
     */
    private JTextArea titol = new JTextArea();


    public vistaNouDoc() {
        setVisible(true);
        setTitle("Crear document");
        setContentPane(lamina);
        setBounds(500, 300, 800, 400);

        bSortir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaGestorDocument();
                setVisible(false);
                dispose();
            }
        });


        bCrear.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (pcreacio.isVisible()) {
                    new Missatge("No pot fer dues creacions alhora");
                }
                else {
                    Map<String, Map<String, Integer>> ta = CtrlPresentacio.getTitolsAutors();
                    if (ta.containsKey(autor.getText())) {
                        if (ta.get(autor.getText()).containsKey(titol.getText())) {
                            new Missatge("Document ja existit, s'ha de introduit un autor o titol diferent");

                        }
                        else {

                            pcreacio = new vistaCreacio(titol.getText(), autor.getText());
                            titol.setText("");
                            autor.setText("");
                        }
                    }
                    else if (titol.getText().length() == 0 || autor.getText().length() == 0) {
                        new Missatge("S'ha de introduir un autor i un titol");
                    }
                    else {

                        pcreacio = new vistaCreacio(titol.getText(), autor.getText());
                        titol.setText("");
                        autor.setText("");
                    }
                }

            }
        });


        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        lamina = new JPanel();
        lamina.setLayout(new BorderLayout(0, 0));
        final JLabel label1 = new JLabel();
        label1.setText("Crear document");
        lamina.add(label1, BorderLayout.NORTH);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        lamina.add(panel1, BorderLayout.CENTER);
        final JLabel label2 = new JLabel();
        label2.setText("Autor");
        panel1.add(label2);
        autor = new JTextArea();
        autor.setAlignmentX(0.5f);
        autor.setLineWrap(true);
        autor.setMinimumSize(new Dimension(200, 15));
        panel1.add(autor);
        final JLabel label3 = new JLabel();
        label3.setText("Titol");
        panel1.add(label3);
        titol = new JTextArea();
        titol.setColumns(0);
        titol.setLineWrap(true);
        titol.setMinimumSize(new Dimension(200, 15));
        panel1.add(titol);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        lamina.add(panel2, BorderLayout.SOUTH);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.add(panel3, BorderLayout.CENTER);
        bSortir = new JButton();
        bSortir.setText("sortir");
        panel3.add(bSortir);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel2.add(panel4, BorderLayout.NORTH);
        bCrear = new JButton();
        bCrear.setText("Iniciar creacio");
        panel4.add(bCrear);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return lamina;
    }

}
