package presentacio;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.FileNotFoundException;


/**
 * Aquesta vista s'encarrega de mostrar totes funcionalitats que es poden fer amb documents i
 * permet anar a la vista que pot realitzar aquestes funcionalitats amb botons
 * @author Zheshuo Lin
 */
public class vistaGestorDocument extends JFrame {

    /**
     * El panell que conte tots components de finestra
     */
    private JPanel lamina;
    /**
     * Títol de la finestra
     */
    private JLabel titolVista;
    /**
     * boto per tancar la finestra i tornar a la menú principal
     */
    private JButton bSortir;
    /**
     * boto per anar a la finestra de crear nou document
     */
    private JButton bNouDoc;
    /**
     * boto per anar a la finestra de modificar document
     */
    private JButton bModificarDoc;
    /**
     * boto per anar a la finestra de eliminar document
     */
    private JButton bEliminarDoc;
    /**
     * boto per anar a la finestra de carregar document
     */
    private JButton bCarregarDoc;
    /**
     * boto per anar a la finestra de guardar document
     */
    private JButton bGuardarDoc;

    public vistaGestorDocument() {
        setBounds(500, 300, 500, 300);
        setContentPane(lamina);
        setResizable(true);
        setTitle("Gestor De Document");

        bSortir.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.iniPresentacio();
                setVisible(false);
                dispose();

            }
        });
        bNouDoc.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaNouDoc();
                setVisible(false);
                dispose();

            }
        });

        bModificarDoc.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaModificarDoc();
                setVisible(false);
                dispose();

            }
        });

        bEliminarDoc.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaEliminarDoc();
                setVisible(false);
                dispose();

            }
        });

        bCarregarDoc.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaCarregarDoc();
            }
        });

        bGuardarDoc.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                CtrlPresentacio.vistaGuardarDoc();
                setVisible(false);
                dispose();
            }
        });
        setVisible(true);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        lamina = new JPanel();
        lamina.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        lamina.add(panel1, BorderLayout.CENTER);
        bNouDoc = new JButton();
        bNouDoc.setText("Nou document");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(bNouDoc, gbc);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(spacer1, gbc);
        bModificarDoc = new JButton();
        bModificarDoc.setText("Modificar document");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(bModificarDoc, gbc);
        bEliminarDoc = new JButton();
        bEliminarDoc.setText("Eliminar document");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(bEliminarDoc, gbc);
        bGuardarDoc = new JButton();
        bGuardarDoc.setText("Guardar document");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(bGuardarDoc, gbc);
        bCarregarDoc = new JButton();
        bCarregarDoc.setText("Carregar document");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(bCarregarDoc, gbc);
        titolVista = new JLabel();
        titolVista.setText("Gestor de document");
        lamina.add(titolVista, BorderLayout.NORTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        lamina.add(panel2, BorderLayout.SOUTH);
        bSortir = new JButton();
        bSortir.setText("sortir");
        panel2.add(bSortir);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return lamina;
    }

}